#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: my-nginx
  #namespace: argocd
#data:  
 # nginx.conf: |
  #  events {}
   # env MY_SECRET;
    #http {
     #   server {
       #     listen 8080;
           # location / {
        #        set_by_lua \$MY_SECRET 'return os.getenv("MY_SECRET")';
            #    return 200 \$MY_SECRET;
           # }
        #}
    #}
---
apiVersion: v1
kind: Secret
metadata:
  name: my-nginx
 # namespace: argocd
  annotations:

    # Our special annotation to tell AVP where the secrets are
    avp.kubernetes.io/path: "secret/data/my-nginx"
stringData:  
  MY_SECRET: <password>

---
