---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-one
  template:
    metadata:
      labels:
        app: sample-app-one
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
        ports:
        - containerPort: 8080
